Field_Name	Data_Type	Nullable	Definition
Goal_Assign_Key	INT PK	No	Surrogate primary key. Auto increment integer assigned by SQL Server using IDENTITY(1,1). Uniquely identifies each goal assignment row. Has no business meaning — exists solely to uniquely identify the row.
Resp_Code	VARCHAR(20) FK	No	Foreign key to Dim_Resp using the natural key. Identifies who this goal is assigned to — an individual person, branch, or department. Using Resp_Code rather than Resp_Key ensures the assignment remains valid across SCD versions if the responsibility entity transfers.
Goal_Key	INT FK	No	Foreign key to Dim_Goal. Identifies which metric this goal is tracking — originations, balance, new accounts, customer satisfaction etc. Dim_Goal carries Unit_Cd which determines how the ETL aggregates actuals and how Goal_Value should be interpreted.
Goal_Version	VARCHAR(20)	No	Identifies which annual plan this goal belongs to. Example: FY2025. Since goals are not revised this also implicitly identifies the fiscal year — one version per year. Must match Goal_Version on FactGoalSnap for the ETL join to work correctly. Used to partition goal history across years in the same table.
Goal_Level	VARCHAR(20)	No	The organisational level this goal is set at. Values: PERSON, BRANCH, DEPARTMENT. Must align with the Resp_Type of the Resp_Code row in Dim_Resp. Carried forward to FactGoalSnap by the ETL. Used to separate goal levels in reports and prevent double counting when rolling up.
Goal_Value	DECIMAL(18,4)	No	The original full-year target. Stores dollars, counts, or decimal percentages in a single column. Unit_Cd on Dim_Goal identifies what this number represents. Examples: 6000000.0000 for a $6M origination goal, 80.0000 for an 80 new account goal, 0.9500 for a 95% satisfaction goal.
Is_Enabled	CHAR(1)	No	Y if this goal assignment is active and should be included in ETL processing and scorecard calculations. N to disable a goal without deleting it — for example if a person leaves mid-year and their goal should no longer be tracked. ETL filters to Is_Enabled = Y when loading FactGoalSnap. Defaults to Y on insert.
Created_Date	DATE	No	The date this goal was manually entered into the system. Used for auditing and tracking when goals were set for each annual cycle.
